export type Language = 'PT' | 'EN' | 'CN';

export const translations = {
    PT: {
        dashboard: "Logistics Command Center",
        dashboardSubtitle: "Overview em tempo real da cadeia de suprimentos e operações de transporte.",
        logistics: "Logistics",
        deliveryPanel: "Painel de Entregas",
        calendar: "Calendario",
        fupReport: "FUP Report",
        vesselUpdates: "Vessel Updates",
        team: "Team",
        admin: "Admin",
        logout: "Sair",
        containersDelivered: "Containers Entregues",
        containersInTransit: "Containers em Trânsito",
        demurrageRisk: "Risco de Demurrage (Atraso)",
        activeWarehouses: "Armazéns Ativos",
        statusOfOperations: "Status das Operações",
        parametrization: "Parametrização",
        demurrageTimeline: "Vencimento Free Time (Demurrage)",
        topWarehouses: "Top 10 Armazéns Alfandegados",
        total: "Total",
        of: "de",
        containers: "containers",
        clickToFilter: "CLIQUE PARA FILTRAR",
        newEntry: "Nova Entrada",
        planEntries: "PLANEJAR ENTRADAS",
        language: "Idioma",
        search: "Buscar...",
        save: "Salvar",
        cancel: "Cancelar"
    },
    EN: {
        dashboard: "Logistics Command Center",
        dashboardSubtitle: "Real-time overview of the supply chain and shipping operations.",
        logistics: "Logistics",
        deliveryPanel: "Delivery Panel",
        calendar: "Calendar",
        fupReport: "FUP Report",
        vesselUpdates: "Vessel Updates",
        team: "Team",
        admin: "Admin",
        logout: "Logout",
        containersDelivered: "Delivered Containers",
        containersInTransit: "Containers in Transit",
        demurrageRisk: "Demurrage Risk",
        activeWarehouses: "Active Warehouses",
        statusOfOperations: "Status of Operations",
        parametrization: "Parametrization",
        demurrageTimeline: "Free Time Expiration (Demurrage)",
        topWarehouses: "Top 10 Bonded Warehouses",
        total: "Total",
        of: "of",
        containers: "containers",
        clickToFilter: "CLICK TO FILTER",
        newEntry: "New Entry",
        planEntries: "PLAN ENTRIES",
        language: "Language",
        search: "Search...",
        save: "Save",
        cancel: "Cancel"
    },
    CN: {
        dashboard: "物流指挥中心",
        dashboardSubtitle: "供应链和运输操作的实时概览。",
        logistics: "物流",
        deliveryPanel: "送货面板",
        calendar: "日历",
        fupReport: "FUP报告",
        vesselUpdates: "船舶更新",
        team: "团队",
        admin: "管理",
        logout: "登出",
        containersDelivered: "已交付集装箱",
        containersInTransit: "在途集装箱",
        demurrageRisk: "滞期费风险 (延迟)",
        activeWarehouses: "活动仓库",
        statusOfOperations: "运营状态",
        parametrization: "参数化",
        demurrageTimeline: "免箱期到期 (滞期费)",
        topWarehouses: "十大保税仓库",
        total: "总计",
        of: "共",
        containers: "集装箱",
        clickToFilter: "点击过滤",
        newEntry: "新条目",
        planEntries: "计划条目",
        language: "语言",
        search: "搜索...",
        save: "保存",
        cancel: "取消"
    }
};

export const getTranslation = (lang: Language, key: keyof typeof translations['PT']) => {
    return translations[lang][key] || translations['EN'][key] || key;
};
